server:
  port: 99
spring:
  application:
    name: cloud-gateway
    #加载环境配置，路由配置，跨域配置
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  profiles:
    active: route,cors
eureka:
  client:
    service-url:
      defaultZone: http://localhost:92/eureka/
---
spring:
  cloud:
    gateway:
      routes:
          #gateway网关的唯一标识
        - id: userService
          #后端微服务的名称，和注册中心的名称一致
          uri: lb://USER-SERVICE
          #断言策略，根据path断言
          predicates:
            - Path=/api/user/**
          #去除前缀
          filters:
            - StripPrefix=1
        #gateway网关的唯一标识
        - id: cityService
          #后端微服务的名称，和注册中心的名称一致
          uri: lb://USER-SERVICE
          #断言策略，根据path断言
          predicates:
            - Path=/api/city/**
          #去除前缀
          filters:
            - StripPrefix=1
  profiles: route

---
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许携带认证信息
            # 允许跨域的源(网站域名/ip)，设置*为全部
            # 允许跨域请求里的head字段，设置*为全部
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            # 跨域允许的有效期
            allow-credentials: true
            allowed-origins: "*"
            #- "http://localhost:8080"
            #- "http://localhost:13010"
            allowed-headers: "*"
            allowed-methods:
              - OPTIONS
              - GET
              - POST
            max-age: 3600
  profiles: cors


